src/main/java/com/ga4w20/bookazon/beans/AccountBackingBean.java
package com.ga4w20.bookazon.beans;

import com.ga4w20.bookazon.entities.Account;
import com.ga4w20.bookazon.persistence.AccountJpaController;
import java.io.Serializable;
import java.security.spec.InvalidKeySpecException;
import java.util.Base64;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Backing Bean for Account that create an Account for the client or manager,
 * make hash and salt password use for registration and Login pages
 * (registration.xhtml , login.xhtml)
 *
 * @author Shirin
 */
@Named("accountBackingBean")
@SessionScoped
public class AccountBackingBean implements Serializable {

    private final static Logger LOG = LoggerFactory.getLogger(AccountBackingBean.class);

    @Inject
    private AccountJpaController accountJpaController;

    private Account account;

    public Account getAccount() {
        if (account == null) {
            account = new Account();
        }
        return account;
    }

    /**
     * This method checks if email address does not exist inside the database,
     * it allows to registration and create an account
     *
     * @author shirin
     * @return
     * @throws InvalidKeySpecException
     */
    public String save() throws InvalidKeySpecException {
        if (accountJpaController.findAccountByEmail(account.getEmail()) != null) {
            return "registration?faces-redirect=true";
        }
        signup();
        accountJpaController.create(account);

        return "login?faces-redirect-true";
    }

    /**
     * This method uses methods inside AccountJpaController for make hash and
     * salt for the password that client entered
     *
     * @author Shirin
     * @throws InvalidKeySpecException
     */
    public void signup() throws InvalidKeySpecException {
        String saltedPassword = accountJpaController.getSalt2();
        byte[] hashedPassword2 = accountJpaController.generateHash(account.getHashedPassword(), saltedPassword);
        account.setSalt(saltedPassword);
        String s = Base64.getEncoder().encodeToString(hashedPassword2);
        account.setHashedPassword(s);
    }

}

src/main/java/com/ga4w20/bookazon/beans/AdsBackingBean.java
package com.ga4w20.bookazon.beans;

import com.ga4w20.bookazon.entities.Ads;
import com.ga4w20.bookazon.persistence.AdsJpaController;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Backing Bean used to store ads from the database for display in index.xhtml
 * @author finley
 */
@Named
@RequestScoped
public class AdsBackingBean implements Serializable {
    private final static Logger LOG = LoggerFactory.getLogger(AdsBackingBean.class);

    @Inject
    private AdsJpaController adsJc;
    private Ads horizontalAd;
    private Ads squareAd;
    private int adType;
    private String adImage;
    private String adRedirect;

    @PostConstruct
    public void init() {
        List<Ads> horizontalAds = this.adsJc.findActiveHorizontalAd();
        List<Ads> squareAds = this.adsJc.findActiveSquareAd();
        if (!horizontalAds.isEmpty()) {
            this.horizontalAd = horizontalAds.get(0);
        }
        if (!squareAds.isEmpty()) {
            this.squareAd = squareAds.get(0);
        }
    }

    public void createAd(){
        Ads ad = new Ads();
        //0 is rectangle, 1 is qaure
        ad.setAdType(this.adType);
        ad.setImage(this.adImage);
        ad.setRedirect(this.adRedirect);
        //Default to 0
        ad.setActiveStatus(0);
        
        this.adsJc.create(ad);
    }
    
    public Ads getHorizontalAd() {
        return horizontalAd;
    }

    public Ads getSquareAd() {
        return squareAd;
    }

    public void setHorizontalAd(Ads horizontalAd) {
        this.horizontalAd = horizontalAd;
    }

    public void setSquareAd(Ads squareAd) {
        this.squareAd = squareAd;
    }
    
    public int getAdType() {
        return adType;
    }

    public void setAdType(int adType) {
        this.adType = adType;
    }

    public String getAdImage() {
        return adImage;
    }

    public void setAdImage(String adImage) {
        this.adImage = adImage;
    }

    public String getAdRedirect() {
        return adRedirect;
    }

    public void setAdRedirect(String adRedirect) {
        this.adRedirect = adRedirect;
    }
}

src/main/java/com/ga4w20/bookazon/beans/BookBackingBean.java
package com.ga4w20.bookazon.beans;

import com.ga4w20.bookazon.entities.Book;
import com.ga4w20.bookazon.persistence.AuthorJpaController;
import com.ga4w20.bookazon.persistence.BookJpaController;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * Backing Bean for Books that initializes some list of books for the front page (index.xhtml)
 * @author Grant
 */
@Named
@SessionScoped
public class BookBackingBean implements Serializable {

    @Inject
    private BookJpaController bjc;
    @Inject
    private AuthorJpaController ajc;
    private List<Book> listRecentBooks;
    private List<Book> listBooksOnSale;
    private boolean searched = false;

    @PostConstruct
    public void init() {
        this.listRecentBooks = this.bjc.getBooksRecentlyAdded();
        this.listBooksOnSale = this.bjc.getBooksOnSale();
    }

    public List<Book> getListRecentBooks() {
        return listRecentBooks;
    }

    public void setListRecentBooks(List<Book> listRecentBooks) {
        this.listRecentBooks = listRecentBooks;
    }

    public boolean isSearched() {
        return searched;
    }

    public void setSearched(boolean searched) {
        this.searched = searched;
    }

    public List<Book> getTopSellers(String genre) {
        return this.bjc.getBooksTopSellers(genre);
    }

    public List<Book> getBooksByAuthor(String isbn, int bookID) {
        String authorName = ajc.getAuthorName(this.bjc.getAuthorIDFromBook(isbn));
        return this.bjc.getBooksFromSameAuthor(authorName, bookID);
    }

    public List<Book> getThreeBooksByGenre(String genre, int bookID) {
        return this.bjc.getThreeBooksByGenre(genre, bookID);
    }

    public List<Book> getBooksByGenre(String genre) {
        return this.bjc.getBooksByGenre(genre);
    }

    public List<Book> getRecentBooks() {
        return this.listRecentBooks;
    }

    public List<Book> getListBooksOnSale() {
        return listBooksOnSale;
    }

    public void setListBooksOnSale(List<Book> listBooksOnSale) {
        this.listBooksOnSale = listBooksOnSale;
    }

}

src/main/java/com/ga4w20/bookazon/beans/CartBackingBean.java
package com.ga4w20.bookazon.beans;

import com.ga4w20.bookazon.entities.Book;
import com.ga4w20.bookazon.persistence.BookJpaController;
import java.io.Serializable;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * Cart Backing Bean that stores the information of a cart to finalize the items in the cart and taxes
 * @author Grant
 */
@Named
@SessionScoped
public class CartBackingBean implements Serializable {
    @Inject
    private BookJpaController bjc;
    @Inject
    private TaxBackingBean tbb;
    private DecimalFormat df;
    private List<Book> listBooksInCart;
    private double subtotal;
    private double total;
    private double gstVal;
    private double hstVal;
    private double pstVal;

    @PostConstruct
    public void init() {
        this.listBooksInCart = new ArrayList<>();
        this.subtotal = 0.0;
        this.total = 0.0;
        this.gstVal = 0.0;
        this.hstVal = 0.0;
        this.pstVal = 0.0;
        this.df = new DecimalFormat("#.##");
        this.df.setRoundingMode(RoundingMode.CEILING);
        this.df.setMinimumFractionDigits(2);
    }

    public int getNumBooksInCart() {
        return this.listBooksInCart.size();
    }

    public void addBook(int id) {
        Book book = this.bjc.findBook(id);
        if (!this.listBooksInCart.contains(book)) {
            subtotal += book.getListPrice();
            this.listBooksInCart.add(book);
            this.setGSTVal();
            this.setHSTVal();
            this.setPSTVal();
            this.setTotal();
        }
    }

    public void removeBook(Book book) {
        if (this.listBooksInCart.contains(book)) {
            this.listBooksInCart.remove(book);
            this.subtotal -= book.getListPrice();
            this.setGSTVal();
            this.setHSTVal();
            this.setPSTVal();
            this.setTotal();
        }
    }

    public List<Book> getListBooksInCart() {
        return this.listBooksInCart;
    }

    public void setListBooksInCart(List<Book> listBooksInCart) {
        this.listBooksInCart = listBooksInCart;
    }

    public String getSubtotal() {
        return this.df.format(this.subtotal);
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public String getTotal() {
        return this.df.format(this.total);
    }

    public void setTotal() {
        this.total = (this.subtotal
                + this.hstVal
                + this.gstVal
                + this.pstVal);
    }

    public String getHSTVal() {
        return this.df.format(this.hstVal);
    }

    public String getGSTVal() {
        return this.df.format(this.gstVal);
    }

    public String getPSTVal() {
        return this.df.format(this.pstVal);
    }

    public void setHSTVal() {
        this.hstVal = this.subtotal * this.tbb.getHST() / 100.0;
    }

    public void setGSTVal() {
        this.gstVal = this.subtotal * this.tbb.getGST() / 100.0;
    }

    public void setPSTVal() {
        this.pstVal = this.subtotal * this.tbb.getPST() / 100.0;
    }

}

src/main/java/com/ga4w20/bookazon/beans/DateRangeBackingBean.java
package com.ga4w20.bookazon.beans;

import java.io.Serializable;
import java.util.Date;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.slf4j.LoggerFactory;

/**
 * Bean used in the manager.xhtml to store data for dates (some data is shown between specified dates)
 * @author Grant
 */
@Named("dateRange")
@SessionScoped
public class DateRangeBackingBean implements Serializable{
    private Date startRange;
    private Date endRange;
    
    public Date getStartRange() {
        return startRange;
    }

    public void setStartRange(Date startRange) {
        this.startRange = startRange;
    }

    public Date getEndRange() {
        return endRange;
    }

    public void setEndRange(Date endRange) {
        this.endRange = endRange;
    }

}

src/main/java/com/ga4w20/bookazon/beans/FileBackingBean.java
package com.ga4w20.bookazon.beans;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.slf4j.LoggerFactory;

/**
 * Backing Bean for Files in the client.xhtml when a client wants to download the books he bought
 * @author Grant
 */
@Named
@RequestScoped
public class FileBackingBean {
    private final static org.slf4j.Logger LOG = LoggerFactory.getLogger(FileBackingBean.class);
    private StreamedContent file;

    public FileBackingBean() throws IOException {
        try {
            LOG.info("Inside file backing bean!");
            InputStream response = new URL("https://ia800700.us.archive.org/35/items/toilersofsea01hugouoft/toilersofsea01hugouoft.pdf").openStream();
            file = new DefaultStreamedContent(response, "application/pdf", "WebProject.pdf");
        } catch (IOException ex) {
            LOG.error(ex.getMessage());
        }
    }

    public StreamedContent getFile() {
        return this.file;
    }
}

src/main/java/com/ga4w20/bookazon/beans/LanguageConfiguration.java
package com.ga4w20.bookazon.beans;

import java.io.Serializable;
import java.util.Locale;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 *
 * @author Alex Bellerive
 */
@Named("language")
@SessionScoped
public class LanguageConfiguration implements Serializable{
    
    private Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
    
    public void setLocale(String newLang){
        this.locale= new Locale(newLang);
        FacesContext.getCurrentInstance().getViewRoot().setLocale(this.locale);
    }
    
    public Locale getLocale(){
        return this.locale;
    }
}

src/main/java/com/ga4w20/bookazon/beans/LoginBackingBean.java
package com.ga4w20.bookazon.beans;

import com.ga4w20.bookazon.entities.Account;
import com.ga4w20.bookazon.persistence.AccountJpaController;
import java.io.Serializable;
import java.security.spec.InvalidKeySpecException;
import java.util.Base64;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class helps for the precess of login of manager or Client
 *
 * @author Shirin 04/2020
 */
@Named("loginBackingBean")
@SessionScoped
public class LoginBackingBean implements Serializable {

    private final static Logger LOG = LoggerFactory.getLogger(LoginBackingBean.class);

    @Inject
    private AccountJpaController accountJpaController;
    private Account account;
    private Account account2;

    public Account getAccount() {
        if (account == null) {
            account = new Account();
        }
        return account;
    }

    public Account getAccountTwo() {
        return this.account2;
    }

    /**
     * This method uses for login of already exist account(client) checks if
     * email exist in the database then checks if password is equal of hash+salt
     * on base of the user if he is a manager redirects to manager page, if he
     * is a client redirects to index page if he is not registered yet,
     * redirects to registration page
     *
     * @author Shirin
     * @return
     * @throws InvalidKeySpecException
     */
    public String submit() throws InvalidKeySpecException {
        account2 = accountJpaController.findAccountByEmail(account.getEmail());
        if (accountJpaController.findAccountByEmail(account.getEmail()) != null && login(account.getHashedPassword(), account2) == true) {
            account = account2;
            if (account.getManagerStatus() == '0' || account.getManagerStatus() == null) {
                return "index?faces-redirect=true";

            } else {
                return "manager?faces-redirect=true";

            }
        } else {
            account = null;
            return "registration?faces-redirect=true";

        }
    }

    /**
     * checks if an account is a manager or normal client
     *
     * @author Shirin
     * @return
     */
    public boolean isManager() {
        return this.account2.getManagerStatus().equals('1');
    }

    /**
     * checks if client signed in or not
     *
     * @author Shirin
     * @return
     */
    public boolean isSignedIn() {
        return account2 != null;
    }

    /**
     * takes out all sessions then no page would recognize this user
     *
     * @author Shirin
     * @return
     */
    public String signOut() {
        // End the session, removing any session state
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();

        // Redirect is necessary to let the browser make a new GET request
        return "index?faces-redirect=true";
    }

    /**
     * it is a helper method for compare a password with salt it helps the
     * methods inside AccountJpaController it gets a password, finds user with
     * the email address, then gets salt string from the database and again make
     * another hash password with help of this salt and just entered password
     * compares with hashed password that exist in the database, if there is a
     * match then login
     *
     * @author Shirin
     * @param inputpass
     *  * @return
     * @throws InvalidKeySpecException
     * @throws InvalidKeySpecException
     * @throws InvalidKeySpecException
     */
    public boolean login(String inputpass, Account account2) throws InvalidKeySpecException, InvalidKeySpecException, InvalidKeySpecException {

        String salt = "";
        String password_hash = null;
        boolean valid = true;

        salt = account2.getSalt();
        password_hash = account2.getHashedPassword();
        byte[] comparehash = accountJpaController.generateHash(inputpass, salt);
        String s = Base64.getEncoder().encodeToString(comparehash);
        if (s.equals(password_hash)) {
            valid = true;
        } else {
            valid = false;
        }

        return valid;
    }

}

src/main/webapp/checkout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!-- Author: Grant -->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <ui:composition template="/template/mainLayout.xhtml">
        <ui:param name="pageTitle" value="#{msgs.checkoutTitle}"/>
        <ui:define name="main_content">
            <div class="ui segment">
                <div class="ui two column divided stackable grid">
                    <div class="column">
                        <h4 class="ui dividing blue header">#{msgs.orderSummary}</h4>
                        <div class="ui vertically divided stackable grid">
                            <ui:repeat value="#{cartBackingBean.listBooksInCart}" var="booksInCart">
                                <div class="one column row">
                                    <div class="column">
                                        <div class="item">
                                            <div class="image">
                                                <h:graphicImage styleClass="ui tiny image" value="/ga4w20/javax.faces.resource/#{booksInCart.imagePath}.xhtml?ln=images"/>
                                            </div>
                                            <div class="content">
                                                <a class="header">#{booksInCart.title}</a>
                                                <div class="meta">
                                                    <span class="author">#{authorJpaController.getAuthorName(bookJpaController.getAuthorIDFromBook(booksInCart.isbn))}</span>
                                                </div>
                                                <div class="meta">
                                                    <span class="pubDate">#{booksInCart.pubDate}</span>
                                                </div>
                                                <div class="extra">
                                                    <h:form>
                                                        <h:commandButton styleClass="ui blue label" value="#{msgs.viewBook}" action="book?faces-redirect=true">
                                                            <f:actionListener binding="#{viewBookBackingBean.setSelectedBook(booksInCart)}"/>
                                                        </h:commandButton>
                                                        <h:commandButton styleClass="ui red label" value="#{msgs.removeBook}" action="checkout?faces-redirect=true">
                                                            <f:ajax render="@none" event="click" onevent="removeBookFromCart(#{booksInCart.bookID})"/>
                                                            <f:actionListener binding="#{cartBackingBean.removeBook(booksInCart)}"/>
                                                        </h:commandButton>
                                                        <p class="floatRight priceList">$#{bookJpaController.priceFormat(booksInCart.listPrice)}</p>
                                                    </h:form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </ui:repeat>
                            <ui:fragment rendered="#{loginBackingBean.signedIn}">
                                <div class="one column row">
                                    <div class="column">
                                        <div class="item">
                                            <div class="content">
                                                <h4 class="header">#{msgs.subtotal}<span class="floatRight priceList">$#{cartBackingBean.subtotal}</span></h4>
                                                <div class="meta">
                                                    <h:outputText styleClass="tax1" id="GST" value="GST (#{taxBackingBean.GST}%)"/>
                                                    <h:outputText class="floatRight taxList" id="GSTVal" value="$#{cartBackingBean.GSTVal}"/>
                                                </div>
                                                <div class="meta">
                                                    <h:outputText styleClass="tax1" id="PST" value="PST (#{taxBackingBean.PST}%)"/>
                                                    <h:outputText class="floatRight taxList" id="PSTVal" value="$#{cartBackingBean.PSTVal}"/>

                                                </div>
                                                <div class="meta">
                                                    <h:outputText styleClass="tax1" id="HST" value="HST (#{taxBackingBean.HST}%)"/>
                                                    <h:outputText class="floatRight taxList" id="HSTVal" value="$#{cartBackingBean.HSTVal}"/>
                                                </div>
                                                <h4 class="header">#{msgs.total}<h:outputText id="total" class="floatRight priceList" value="$#{cartBackingBean.total}"/></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </ui:fragment>
                        </div>
                    </div>
                    <div class="column">
                        <ui:fragment rendered="#{!loginBackingBean.signedIn}">
                            <div class="ui center aligned header">
                                #{msgs.mustLogin}
                            </div>
                        </ui:fragment>
                        <ui:fragment rendered="#{loginBackingBean.signedIn}">
                            <h4 class="ui dividing blue header">#{msgs.billing}</h4>
                            <h:form styleClass="ui form" onsubmit="deleteAllCookies();">
                                <div class="fields">
                                    <div class="eight wide required field">
                                        <h:message for="fNameOnCard" styleClass="errorMsg"/>
                                        <h:outputLabel>#{msgs.fname} #{msgs.onCard}</h:outputLabel>
                                        <h:inputText id="fNameOnCard" validator="#{payment.validateName}" value="#{payment.firstNameOnCard}" pt:placeholder="#{loginBackingBean.account.FName}"/> 

                                    </div>
                                    <div class="eight wide required field">
                                        <h:message for="lNameOnCard" styleClass="errorMsg"/>
                                        <h:outputLabel>#{msgs.lname} #{msgs.onCard}</h:outputLabel>
                                        <h:inputText id="lNameOnCard" validator="#{payment.validateName}" value="#{payment.lastNameOnCard}" pt:placeholder="#{loginBackingBean.account.LName}"/> 

                                    </div>
                                </div>
                                <div class="required field">
                                    <h:message for="billAddress" styleClass="errorMsg"/>
                                    <h:outputLabel>#{msgs.billAdd}</h:outputLabel>
                                    <h:inputText id="billAddress" validator="#{payment.validateName}" value="#{payment.billAddress}" pt:placeholder="#{loginBackingBean.account.address}"/> 

                                </div>
                                <div class="required field">
                                    <h:message for="cardType" styleClass="errorMsg"/>
                                    <h:outputLabel>#{msgs.card}</h:outputLabel>
                                    <h:selectOneMenu id="cardType" validator="#{payment.validateCardType}" value="#{payment.cardType}" styleClass="ui fluid dropdown">
                                        <f:selectItem itemValue="Visa" itemLabel="Visa"/>
                                        <f:selectItem itemValue="Mastercard" itemLabel="Mastercard"/>
                                    </h:selectOneMenu>
                                </div>
                                <div class="fields">
                                    <div class="six wide required field">
                                        <h:message for="cardNumber" styleClass="errorMsg"/>
                                        <h:outputLabel>#{msgs.cardnum}</h:outputLabel>
                                        <h:inputText id="cardNumber" validator="#{payment.validateCardNum}" maxlength="16" value="#{payment.cardNumber}" pt:placeholder="Card Number"/> 
                                    </div>
                                    <div class="five wide required field">
                                        <h:message for="cardCVC" styleClass="errorMsg"/>
                                        <h:outputLabel>CVC</h:outputLabel>
                                        <h:inputText id="cardCVC" validator="#{payment.validateCardCVC}" maxlength="3" value="#{payment.cardCVC}" pt:placeholder="CVC"/> 
                                    </div>
                                    <div class="five wide required field">
                                        <h:message for="cardExp" styleClass="errorMsg"/>
                                        <h:outputLabel>#{msgs.exp}</h:outputLabel>
                                        <h:inputText id="cardExp" label="#{msgs.exp}"
                                                     value="#{payment.cardExp}" pt:placeholder="MM/YYYY">
                                            <f:convertDateTime pattern="MM/yyyy" />
                                        </h:inputText>
                                    </div>
                                </div>
                                <h:commandButton styleClass="ui blue button" type="submit" value="#{msgs.buyBook}" action="client?faces-redirect=true">
                                    <f:actionListener binding="#{saleJpaController.buyBooks(cartBackingBean.listBooksInCart, taxBackingBean.GST, taxBackingBean.HST, taxBackingBean.PST, loginBackingBean.account)}"/>
                                    <f:actionListener binding="#{cartBackingBean.init()}"/>
                                </h:commandButton>
                            </h:form>  
                        </ui:fragment>
                    </div>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<!--Author: Shirin & Grant-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template/layout.xhtml">
        <ui:param name="pageTitle" value="#{msgs.loginTitle}"/>
        <ui:define name="main_content">
            <div class="ui segment">
                <div class="ui doubling centered card">
                    <div class="image">
                        <h:graphicImage styleClass="ui medium circular centered image" library="images" name="avatar.jpg" />
                    </div>
                    <h:form styleClass="ui form">
                        <div class="field">
                            <h:outputLabel styleClass="center aligned header" for="email">Username</h:outputLabel>
                            <h:inputText id="email" styleClass="center aligned" value="#{loginBackingBean.account.email}" pt:placeholder="#{msgs.email}">
                                <f:ajax event="blur" execute="@this" render="validation-messages"/>   
                            </h:inputText>
                            <h:messages id="validation-messages" style="color:red"/>
                        </div>
                        <div class="field">
                            <h:outputLabel styleClass="center aligned header" for="hashedPassword">Password</h:outputLabel>
                            <h:inputSecret styleClass="center aligned" id="hashedPassword" value="#{loginBackingBean.account.hashedPassword}" pt:placeholder="#{msgs.password}">
                                <f:ajax event="blur"  render="validation-messages"/>
                            </h:inputSecret>
                        </div>
                        <h:commandButton styleClass="ui blue fluid button" id="save" value="Login" action="#{loginBackingBean.submit()}">
                            <f:actionListener binding="#{taxBackingBean.setTaxes(loginBackingBean.accountTwo.province)}"/>
                        </h:commandButton>
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>